### PR TITLE
Gradle 6.2 as minimum (re-merge of #251)

### LINKED ISSUE #267: `null` passed for credentails (at least) in e2e-tests
After https://github.com/gradle-nexus/publish-plugin/commit/535705a3771ae83f57ac7e354240442cd139636e the e2e-tests fails with 401 Unauthorized. Some quick debugging shows that `null` values are passed for credentials. To be verified if there is problem with passing the values from e2e-tests or (rather) how to fix a regression which might affect also regular plugin users.

### PR DESCRIPTION
**Pull request by TWiStErRob**
* Fixes #267
 * Re-merge of #251
 * 251 was reverted in #268
 * This PR reverts #268

### CODE REVIEW

File: src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt [hunk 1]
```diff
@@ -102,8 +102,8 @@ class NexusPublishPlugin : Plugin<Project> {
             stagingRepositoryId.convention(registryService.map { it.registry[repository.get().name].stagingRepositoryId })
         }
         extension.repositories.all {
-            username.convention(rootProject.providers.gradleProperty("${name}Username").forUseAtConfigurationTimeCompat())
-            password.convention(rootProject.providers.gradleProperty("${name}Password").forUseAtConfigurationTimeCompat())
+            username.convention(rootProject.provider { rootProject.findProperty("${name}Username") as? String })
+            password.convention(rootProject.provider { rootProject.findProperty("${name}Password") as? String })
```
Comment (TWiStErRob) [inline src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt]: Soooo, good ol' [Murphy](https://en.wikipedia.org/wiki/Murphy%27s_law) has hit us. @szpak do you remember these conversations:

> I wonder, how many people could use the other cases mentioned in javadoc?
https://github.com/gradle-nexus/publish-plugin/pull/242#discussion_r1258921238

> ... and if someone does use it, and want it, they'll hopefully tell us :)
https://github.com/gradle-nexus/publish-plugin/pull/251#discussion_r1270942973

Yes, [E2E tests are using exactly those esoteric features](https://github.com/gradle-nexus/nexus-publish-e2e-minimal/blob/ac03ac44e67c28f59d065af252c5234ab96e60bb/build.gradle#L33)...

```gradle
project.ext[propertyNameToOverride] = project.getProperty("$e2ePropertyNameToOverride")
```

To re-test the rest of the #251 PR, for now I reverted the use of `gradleProperty` change in 8e96e5eb3c6cb1d3a00cc9d9c254443ced17d7c7

File: src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt [hunk 2]
```diff
@@ -100,13 +98,14 @@ class NexusPublishPlugin : Plugin<Project> {
         }
         rootProject.tasks.withType(AbstractTransitionNexusStagingRepositoryTask::class.java).configureEach {
             transitionCheckOptions.convention(extension.transitionCheckOptions)
-            stagingRepositoryId.convention(registry.map { it[repository.get().name].stagingRepositoryId })
+            usesService(registryService)
+            stagingRepositoryId.convention(registryService.map { it.registry[repository.get().name].stagingRepositoryId })
         }
         extension.repositories.all {
             username.convention(rootProject.provider { rootProject.findProperty("${name}Username") as? String })
             password.convention(rootProject.provider { rootProject.findProperty("${name}Password") as? String })
```
Comment (TWiStErRob) [inline src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt:106]: E2E test execution queued for [8e96e5e](https://github.com/gradle-nexus/publish-plugin/pull/274/commits/8e96e5eb3c6cb1d3a00cc9d9c254443ced17d7c7): https://github.com/gradle-nexus/publish-plugin/actions/runs/6224526816 (a copy of the branch)

File: src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt (hunk 1 above)
Comment (TWiStErRob) [reply src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt]: I propose to merge this PR without these two lines of change, and revisit it separately, because of the potential changes needed in E2E tests.

Comment (szpak) [reply src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt]: Sound good for me. Maybe also some other external projects use that "esoteric feature" :-).

**Review by szpak — APPROVED** [review]
LGTM, feel free to merge once ready.

**Review by Goooler — APPROVED** [review]

**Comment by szpak** [comment]
@TWiStErRob Can be merge it?
