### PR TITLE
[#52] Accept both RELEASED and NOT_FOUND states on release

### LINKED ISSUE #52: Staging repository is not in desired state (not_found): StagingRepository(id=orgpostgresql-1612804902325, state=released, transitioning=false)
I've the following (I use https://github.com/vlsi/nexus-stub as a poorman's Nexus).

Are you sure `state=release, transitioning=false` is not valid state for Nexus as it promotes a staging repository?

AFAIK GNSP required either `not_found` or `released` state (see `(expected [released, not_found])` in https://github.com/Codearte/gradle-nexus-staging-plugin/issues/110#issue-425034006 )

`publish-plugin`:

```
    Execution failed for task ':releaseNexusStagingRepository':
        io.github.gradlenexus.publishplugin.RepositoryTransitionException: Staging repository is not in desired state (not_found): StagingRepository(id=orgpostgresql-1612804902325, state=released, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation. If not, please report it to https://github.com/gradle-nexus/publish-plugin/issues/ with '--info' logs
            at io.github.gradlenexus.publishplugin.internal.StagingRepositoryTransitioner.assertRepositoryInDesiredState(StagingRepositoryTransitioner.kt:62)
            at io.github.gradlenexus.publishplugin.internal.StagingRepositoryTransitioner.effectivelyChangeState(StagingRepositoryTransitioner.kt:42)
            at io.github.gradlenexus.publishplugin.internal.StagingRepositoryTransitioner.effectivelyRelease(StagingRepositoryTransitioner.kt:35)
            at io.github.gradlenexus.publishplugin.ReleaseNexusStagingRepository.transitionStagingRepo(ReleaseNexusStagingRepository.kt:40)
            at io.github.gradlenexus.publishplugin.AbstractTransitionNexusStagingRepositoryTask.transitionStagingRepo(AbstractTransitionNexusStagingRepositoryTask.kt:66)
            at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
```

### PR DESCRIPTION
**Pull request by szpak**
As spotted by @vlsi both RELEASED and NOT_FOUND returned from Nexus are valid.

Fixes #52.

### CODE REVIEW

File: src/main/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitioner.kt [hunk 1]
```diff
@@ -32,14 +32,14 @@ class StagingRepositoryTransitioner(val nexusClient: NexusClient, val retrier: A
 
     //TODO: Add support for autoDrop=false
```
Comment (vlsi) [inline src/main/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitioner.kt:33]: The `TODO` comment might probably be removed now :)

Comment (szpak) [reply src/main/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitioner.kt]: Might be :).

Nevertheless, we could allow users to disable requesting by the plugin autoDrop in Nexus.

**Review by marcphilipp — APPROVED** [review]
